services:
  pg:
    image: postgres:13.15-alpine3.20
    container_name: pg
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgressql/data
    ports:
      - 0.0.0.0:5432:5432

